name: tag ref main

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
    tag_ref_main:
        name: Print Baz!
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2
        
            - name: Check if tag is on main branch
              id: check_tag
              run: |
                if [ "$(git branch --contains $(git rev-parse HEAD) | grep main)" ]; then
                  echo "tag_on_main=true" >> $GITHUB_ENV
                else
                  echo "tag_on_main=false" >> $GITHUB_ENV
                fi
            
            - name: print baz
              if: env.tag_on_main == 'true'
              run: |
                echo "이 태그는 main 브랜치로부터 생성되었읍니다."